[application]
default_platform = "web"

# Relative to pandox-web crate
tailwind_input = "tailwind.css"
tailwind_output = "assets/tailwind.compiled.css"
public_dir = "../../modules"

[web.app]
title = "Pandox"

[web.watcher]
reload_html = true